# Generated by Django 2.0 on 2018-10-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181018_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtype',
            name='type_img',
            field=models.ImageField(default='type/default.png', upload_to='type/', verbose_name='缩略图'),
        ),
    ]
